### ISSUE TITLE
No Teams are found at all.

### ISSUE THREAD

**Issue by appcoders** [leeford/Backup-Team#3]
I created the app registration and fill in the parameters for client and tenant id, Device Login Auth does work, but if I try to search for one or even all teams, nothing is found.

**Comment by appcoders** [comment]
Just seen that I got FAILED Insufficient priviliges to complete the operation. But I have all needed permission given:

<img width="722" alt="screen_2021-10-27-13-30-37@2x" src="https://user-images.githubusercontent.com/4519870/139057413-7b624b9d-8466-4a04-adfd-e6a8d62ab9b8.png">

**Comment by leeford** [comment]
Hi,

You will need the following `Delegated` permissions granted to your app registration:

* Team.ReadWrite.All
* User.ReadBasic.All

Currently you have `Application` permissions assigned (not used by user when authenticated)

(I've just created an app registration with these permissions and got a Team list OK)

**Comment by appcoders** [comment]
Thanks a lot. Issue fix.
