### ISSUE TITLE
Sign-in error 

### ISSUE THREAD

**Issue by john-janek** [leeford/Backup-Team#5]
Hi! 

Trying to execute the script and get this error after logging into the device login. 

```
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\\Downloads\Backup-Team-1.0.3\Backup-Team-1.0.3\Backup-Team.ps1:100 char:55
+ ...            $errorMessage = $_.ErrorDetails.Message | ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJs
   onCommand


FAILED TO SIGNIN
```
I've thrown some simple debug prints, and it looks like it is getting the return from Microsoft but the format isn't expected and/or it doesn't know what to do with it. Is anyone else reporting this problem?

**Comment by leeford** [comment]
Hi,

Let me see if I can replicate this. Just confirm, you are using PowerShell Core and not Windows PowerShell, as this can cause issues.

Thanks.

**Comment by john-janek** [comment]
Hi @leeford! Yep, that was it.

So even on Windows 11, the shipping PowerShell is still 5.1 🤯 - updated to 7.1 and worked like a champ. Awesome script.

If I get a bit of time, I might submit a merge request to do a version check. 

Thanks so much for your time on this!
